---
title: 本博客的建立及部署 -- 使用 blogdown + Vercel 快速建立博客
author: Tintingo
date: '2022-02-16'
slug: establish-blog-hugo
show_toc: false
toc_depth: 3
categories:
  - Blog
tags:
  - Blog
  - Emacs
  - Doom Emacs
  - 效率工具
---


本篇文章来讲一下我建立本博客的过程以及撰写博客的工作流程，希望对那些与我一样想拥有自己的个人博客的朋友一些帮助。
首先说明一下建立本博客所需的最简工具流程：

1. 在 Rstudio 中使用 =blogdown= 包，可以轻松建立一个本地的 hugo 博客。
2. 将文件上传至个人的 github 仓库并使用 Vercel 发布到网上。
3. 如果想使用自己的域名的话，就申请一个域名并备案，将域名 DNS 解析到 Vercel 给你指定的网址上。

在我尝试的建立个人博客的方法中，这是成本最低、最方便的一个了。甚至不需要花钱租服务器，不需要 hugo、前端知识，就可以建立一个在国内访问速度还不错的网站了。此外，该流程还具有以下的优势：
1. 由 hugo 静态博客框架所带来的 =速度快= , =文章本地化= 等优势；
2. 与 github 结合所带来的 =版本控制= 等优势；
3. hugo 竟然支持 org 格式的文件，这意味着可以使用 Emacs 方便地写博客了。

* 使用 blogdown + Vercel 快速建立博客
在将博客迁移到 hugo 之前，我还尝试过 wordpress、typoche 等动态博客框架，并分别使用了很长一段时间。但是在使用动态博客框架的时候，我从来没有感觉到博客是真正属于自己的，因为文章都在云上，难以给人安全感。后来我无意中看了谢益辉博士在 [[https://www.bilibili.com/video/BV1ZK4y1s7ir?from=search&seid=9394683960598560609&spm_id_from=333.337.0.0][CGM]] 上有关 =blogdown= 的讲座，才发现静态博客才是我真正需要的。并且有了 =blogdown= 这个工具，使得搭建 hugo 静态博客的流程变得非常简单。因此下定决心将博客迁移到 hugo 中。

本来我想从头说一下建博客的过程，后来觉得这个过程实在太简单，也没有什么记录下来的必要。网上有几篇文章也说的很清楚了，跟着做应该不会踩雷，因此详细安装过程见下面的链接吧。

1. [[https://www.bilibili.com/video/BV1ZK4y1s7ir?from=search&seid=9394683960598560609&spm_id_from=333.337.0.0][谢益辉博士讲座的B站视频《用 blogdown 搭建一个静态网站》]]
2. [[https://cloud.tencent.com/developer/article/1851491][R沟通｜使用 Blogdown 构建个人博客]]

简单说来就是以下几点：

1. 安装 [[https://www.r-project.org/][R语言]] 及 [[https://www.rstudio.com/products/rstudio/download/#download][RStudio]]，还有 git（不会有人没装 git 吧）
2. 安装 =blogdown= 包
   #+begin_src r
 install.packages("blogdown")

   #+end_src
3. 创建一个 =Website using blogdown= 项目并启动；
   #+begin_src shell
    # 启动server
    blogdown:::serve_site()
    # 停止server
    blogdown::stop_server()
   #+end_src

到这里大家应该就可以在本地预览到生成的网站的样子了。这里显示的是 blogdown 自带的默认模板，可以去网上找一个 [[https://hugothemesfree.com/tag/blog/][hugo模板]] 先用着。一开始切记不要在挑主题换主题上花太多时间，将网站建好并创作出足够多的文章后，再考虑折腾主题，不然容易在形形色色的主题中浪费太多时间。

注意很有可能你在网上找到的文章，在发布博客的时候选择的都是使用 netlify 发布。我一开始使用的也使 netlify，但在体验了几天后，发现 netlify 托管的网站，在国外访问的速度是比较快的，但是国内打开速度很慢。

因此我目前的方案是使用 Vercel 进行发布，使用过程与 netlify 挺像的，都是使用 github 登陆后授权个人仓库，自动部署网站并提供随机生成的域名，我们就可以直接使用这个域名访问博客了。如果你想跟我一个拥有一个自己的个性域名的话，需要购买一个域名并备案（如果购买的是国内的域名的话）。我购买的是 [[https://wanwang.aliyun.com/domain/][阿里云万网]] 的域名，不同域名的价格不同，输入域名之后会有个报价，觉得合适的话可以选择购买。
